/**
 * Regenerates `public/sitemap.xml` from the source of truth:
 *   - `ALL_PUBLIC_PATHS` in src/config/pages.ts
 *   - `LANGUAGES` in src/config/site.ts
 *
 * Run with: bun run sitemap
 *
 * Each indexable page is emitted once (default-language, unprefixed URL) with a
 * full `xhtml:link` hreflang alternate set for all 30 languages plus
 * x-default — search engines discover the localized variants through it.
 */
import { ALL_PUBLIC_PATHS } from '../src/config/pages';
import { LANGUAGES, siteConfig } from '../src/config/site';

const origin = (siteConfig.url || 'https://webauditpro.example.com').replace(/\/$/, '');
const defaultLang = siteConfig.defaultLanguage;

function localizedPath(path: string, code: string): string {
  const clean = path ? `/${path.replace(/^\//, '')}` : '/';
  if (code === defaultLang) return clean;
  return clean === '/' ? `/${code}` : `/${code}${clean}`;
}

function urlBlock(path: string): string {
  const loc = `${origin}${localizedPath(path, defaultLang)}`;
  const links = LANGUAGES.map(
    (lang) =>
      `    <xhtml:link rel="alternate" hreflang="${lang.code}" href="${origin}${localizedPath(path, lang.code)}"/>`,
  );
  const xDefault = `    <xhtml:link rel="alternate" hreflang="x-default" href="${loc}"/>`;
  return ['  <url>', `    <loc>${loc}</loc>`, ...links, xDefault, '  </url>'].join('\n');
}

const today = new Date().toISOString().slice(0, 10);

const xml = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  // The XML declaration must stay first; the note goes in the prolog after it.
  `<!-- Generated by \`bun run sitemap\` — do not edit by hand. lastmod: ${today} -->`,
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">',
  ...ALL_PUBLIC_PATHS.map(urlBlock),
  '</urlset>',
  '',
].join('\n');

await Bun.write('public/sitemap.xml', xml);
process.stdout.write(
  `sitemap.xml written: ${ALL_PUBLIC_PATHS.length} pages × ${LANGUAGES.length} languages\n`,
);
